# Section 01: Transforming Data with dplyr
### `01- Selecting columns`
Select the following four columns from the counties variable:

- state
- county
- population
- poverty

You don't need to save the result to a variable.
- Select the columns listed from the counties variable.

In [32]:
library(dplyr)
counties <- read.csv("D:\\0000\\GitHub\\Data_Scientist_with_R\\00_Datasets\\counties.csv", 
                    header=TRUE)

In [33]:
counties %>%
  # Select the columns
  select(state, county, population, poverty)

     state     county        population poverty
1    Alabama   "Autauga"      55221     12.9
2    Alabama   "Baldwin"     195121     13.4
3    Alabama   "Barbour"      26932     26.7
4    Alabama   "Bibb"         22604     16.8
5    Alabama   "Blount"       57710     16.7
6    Alabama   "Bullock"      10678     24.6
7    Alabama   "Butler"       20354     25.4
8    Alabama   "Calhoun"     116648     20.5
9    Alabama   "Chambers"     34079     21.6
10   Alabama   "Cherokee"     26008     19.2
11   Alabama   "Chilton"      43819     19.1
12   Alabama   "Choctaw"      13395     23.4
13   Alabama   "Clarke"       25070     24.7
14   Alabama   "Clay"         13537     16.7
15   Alabama   "Cleburne"     15002     17.0
16   Alabama   "Coffee"       50884     17.1
17   Alabama   "Colbert"      54444     17.4
18   Alabama   "Conecuh"      12865     33.8
19   Alabama   "Coosa"        11027     19.3
20   Alabama   "Covington"    37886     20.2
21   Alabama   "Crenshaw"     13938     16.7
22   Alabama   "Cullman"      80965     18.5
23   Alabama   "Dale"         49866     19.1
24   Alabama   "Dallas"       42154     35.0
25   Alabama   "DeKalb"       71068     18.7
26   Alabama   "Elmore"       80763     13.6
27   Alabama   "Escambia"     37935     24.2
28   Alabama   "Etowah"      103766     19.7
29   Alabama   "Fayette"      16896     18.3
30   Alabama   "Franklin"     31634     22.5
⋮    ⋮         ⋮             ⋮          ⋮
3109 Wisconsin "Washburn"     15700     13.1
3110 Wisconsin "Washington"  132921      5.6
3111 Wisconsin "Waukesha"    393873      5.3
3112 Wisconsin "Waupaca"      52125     10.4
3113 Wisconsin "Waushara"     24321     10.3
3114 Wisconsin "Winnebago"   169004     12.0
3115 Wisconsin "Wood"         74012     11.0
3116 Wyoming   "Albany"       37565     26.9
3117 Wyoming   "Big Horn"     11895     12.1
3118 Wyoming   "Campbell"     48013      7.2
3119 Wyoming   "Carbon"       15739     15.3
3120 Wyoming   "Converse"     14101      9.4
3121 Wyoming   "Crook"         7229      5.0
3122 Wyoming   "Fremont"      40755     14.2
3123 Wyoming   "Goshen"       13544     17.9
3124 Wyoming   "Hot Springs"   4809     10.7
3125 Wyoming   "Johnson"       8600      6.3
3126 Wyoming   "Laramie"      95431     10.1
3127 Wyoming   "Lincoln"      18316      7.9
3128 Wyoming   "Natrona"      80011     10.7
3129 Wyoming   "Niobrara"      2516     14.9
3130 Wyoming   "Park"         28985      7.2
3131 Wyoming   "Platte"        8750     16.1
3132 Wyoming   "Sheridan"     29738      8.3
3133 Wyoming   "Sublette"     10117      8.1
3134 Wyoming   "Sweetwater"   44772     11.5
3135 Wyoming   "Teton"        22311      7.4
3136 Wyoming   "Uinta"        20930     13.7
3137 Wyoming   "Washakie"      8400     13.8
3138 Wyoming   "Weston"        7152     14.1

### `02-Arranging observations`
- Add a verb to sort the observations of the `public_work` variable in descending order.

In [34]:
counties_selected <- counties %>%
  select(state, county, population, private_work, public_work, self_employed)

counties_selected %>%
  # Add a verb to sort in descending order of public_work
  arrange(desc(public_work))

     state      county                       population private_work
1    Hawaii     "Kalawao"                       85      25.0
2    Alaska     "Yukon-Koyukuk Census Area"   5644      33.3
3    Wisconsin  "Menominee"                   4451      36.8
4    North Dako ta   "Sioux"                  4380      32.9
5    South Dako ta   "Todd"                   9942      34.4
6    Alaska     "Lake and Peninsula Borough"  1474      42.2
7    California "Lassen"                     32645      42.6
8    South Dako ta   "Buffalo"                2038      48.4
9    South Dako ta   "Dewey"                  5579      34.9
10   Texas      "Kenedy"                       565      51.9
11   North Dako ta   "Rolette"               14498      44.3
12   Arizona    "Apache"                     72124      50.2
13   Alaska     "Bethel Census Area"         17776      53.2
14   Utah       "Daggett"                      776      47.7
15   Alaska     "Nome Census Area"            9854      50.6
16   New Mexico "Mora"                        4660      50.7
17   Alaska     "Northwest Arctic Borough"    7732      54.0
18   Montana    "Big Horn"                   13141      47.7
19   Nevada     "Lincoln"                     5194      50.1
20   South Dako ta   "Jackson"                3237      34.1
21   New Mexico "Harding"                      565      46.3
22   Montana    "Roosevelt"                  11072      45.0
23   California "Sierra"                      3021      45.0
24   Georgia    "Calhoun"                     6489      53.2
25   South Dako ta   "Ziebach"                2833      40.9
26   South Dako ta   "Corson"                 4149      36.1
27   Washington "Ferry"                       7652      52.4
28   Texas      "Brewster"                    9235      49.2
29   South Dako ta   "Mellette"               2086      37.3
30   New Mexico "Catron"                      3583      50.3
⋮    ⋮          ⋮                            ⋮          ⋮
3109 North Dako ta   "Steele"                  1979     72.8
3110 Pennsylvan ia   "Chester"               509797     85.9
3111 Pennsylvan ia   "Lehigh"                356756     87.0
3112 Wisconsin  "Ozaukee"                     87273     85.5
3113 Indiana    "Dubois"                      42291     87.1
3114 Iowa       "Carroll"                     20629     81.5
3115 Missouri   "Taney"                       53555     82.8
3116 Illinois   "Edwards"                      6649     85.8
3117 Pennsylvan ia   "Wyoming"                28147     85.1
3118 Wisconsin  "Waukesha"                   393873     87.4
3119 Michigan   "Allegan"                    112837     85.2
3120 Nebraska   "Colfax"                      10522     83.3
3121 Pennsylvan ia   "Lancaster"             530216     84.7
3122 Wisconsin  "Washington"                 132921     87.7
3123 Pennsylvan ia   "Montgomery"            812970     86.2
3124 Arkansas   "Benton"                     238198     85.9
3125 Iowa       "Winnebago"                   10614     84.3
3126 Indiana    "Elkhart"                    200685     87.5
3127 Indiana    "Gibson"                      33668     88.0
3128 Michigan   "Kent"                       622590     87.3
3129 Pennsylvan ia   "Elk"                    31370     87.1
3130 Indiana    "Bartholomew"                 79488     87.8
3131 Illinois   "Jersey"                      22625     86.6
3132 Indiana    "Clinton"                     32835     87.5
3133 Nebraska   "Dakota"                      20798     87.3
3134 Indiana    "Kosciusko"                   77983     88.3
3135 Indiana    "Spencer"                     20856     86.3
3136 Indiana    "LaGrange"                    38084     84.1
3137 Nebraska   "McPherson"                     433     69.4
3138 Ohio       "Holmes"                      43436     81.3
     public_work self_employed
1    64.1        10.9
2    61.7         5.1
3    59.1         3.7
4    56.8        10.2
5    55.0         9.8
6    51.6         6.1
7    50.5         6.8
8    49.5         1.8
9    49.2        14.7
10   48.1         0.0
11   46.6         8.7
12   45.0         4.7
13   44.8         2.0
14   44.1         8.1
15   44.0         5.2
16   43.9         5.2
17   43.7         2.1
18   43.2         8.7
19   43.1         6.6
20   43.1        21.5
21   42.9        10.7
22   42.8        11.3
23   42.3         9.7
24   42.3         4.4
25   41.7        16.6
26   40.8        21.5
27   40.6         6.4
28   40.4         9.0
29   39.9        22.4
30   39.7         8.3
⋮    ⋮           ⋮
3109 8.5         18.1
3110 8.5          5.5
3111 8.5          4.4
3112 8.5          5.7
3113 8.4          4.4
3114 8.4         10.0
3115 8.4          8.8
3116 8.3          5.9
3117 8.3          6.4
3118 8.3          4.2
3119 8.2          6.4
3120 8.2          8.3
3121 8.2          6.8
3122 8.2          4.1
3123 8.1          5.5
3124 8.0          5.9
3125 7.9          7.5
3126 7.7          4.6
3127 7.7          4.2
3128 7.7          4.9
3129 7.7          4.9
3130 7.6          4.5
3131 7.5          5.8
3132 7.5          4.9
3133 7.3          5.2
3134 6.9          4.7
3135 6.9          6.7
3136 6.6          8.7
3137 5.9         23.9
3138 5.8         12.3

### `03-Filtering for conditions`
- Find only the counties that have a population above one million (1000000).

In [35]:
counties_selected <- counties %>%
  select(state, county, population)

counties_selected %>%
  # Filter for counties with a population above 1000000
  filter(population > 1000000)

   state      county              population
1  Arizona    "Maricopa"           4018143
2  California "Alameda"            1584983
3  California "Contra Costa"       1096068
4  California "Los Angeles"       10038388
5  California "Orange"             3116069
6  California "Riverside"          2298032
7  California "Sacramento"         1465832
8  California "San Bernardino"     2094769
9  California "San Diego"          3223096
10 California "Santa Clara"        1868149
11 Florida    "Broward"            1843152
12 Florida    "Hillsborough"       1302884
13 Florida    "Miami-Dade"         2639042
14 Florida    "Orange"             1229039
15 Florida    "Palm Beach"         1378806
16 Illinois   "Cook"               5236393
17 Maryland   "Montgomery"         1017859
18 Massachuse tts  "Middlesex"     1556116
19 Michigan   "Oakland"            1229503
20 Michigan   "Wayne"              1778969
21 Minnesota  "Hennepin"           1197776
22 Missouri   "St. Louis"          1001327
23 Nevada     "Clark"              2035572
24 New York   "Bronx"              1428357
25 New York   "Kings"              2595259
26 New York   "Nassau"             1354612
27 New York   "New York"           1629507
28 New York   "Queens"             2301139
29 New York   "Suffolk"            1501373
30 Ohio       "Cuyahoga"           1263189
31 Ohio       "Franklin"           1215761
32 Pennsylvan ia   "Allegheny"     1231145
33 Pennsylvan ia   "Philadelphia"  1555072
34 Texas      "Bexar"              1825502
35 Texas      "Dallas"             2485003
36 Texas      "Harris"             4356362
37 Texas      "Tarrant"            1914526
38 Texas      "Travis"             1121645
39 Utah       "Salt Lake"          1078958
40 Virginia   "Fairfax"            1128722
41 Washington "King"               2045756

- Find only the counties in the state of California that also have a population above one million (`1000000`).

In [37]:
counties_selected <- counties %>%
  select(state, county, population)

counties_selected %>%
  # Filter for counties with a population above 1000000
  filter(state == "California", population > 1000000)

  state      county           population
1 California "Alameda"         1584983
2 California "Contra Costa"    1096068
3 California "Los Angeles"    10038388
4 California "Orange"          3116069
5 California "Riverside"       2298032
6 California "Sacramento"      1465832
7 California "San Bernardino"  2094769
8 California "San Diego"       3223096
9 California "Santa Clara"     1868149